SecretKeyFile: "ga-api-test-pramod-bdbcfaf2b1cc.json"
HPEDesignAccountOwner: "jacquot@hpe.com"
HPEDEVAccountOwner: "didier.lalli@hpe.com"
GrommetAccountOwner: "mike.walrath@hpe.com"
HPEGreenLakeccountOwner: "chris.grandinetti@hpe.com"
HPEOneSphereAccountOwner: "scampbell@hpe.com"
OneViewAccountOwner: "edgar.circenis@hpe.com"
HPEGlobalDashccountOwner: "hpe.global.dashboard@gmail.com"
